name: CI (Windows CUDA 13.3)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-self-hosted.yml'
      - '.github/actions/windows-setup-cuda/**'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cu'
      - '**/*.cuh'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/build-self-hosted.yml'
      - '.github/actions/windows-setup-cuda/**'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cu'
      - '**/*.cuh'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows-x64-cuda:
    name: Windows x64 CUDA 13.3 build
    runs-on: windows-2022

    steps:
      - name: Clone
        uses: actions/checkout@v6

      - name: Install CUDA 13.3
        uses: ./.github/actions/windows-setup-cuda
        with:
          cuda_version: '13.3'

      - name: Install Ninja
        shell: pwsh
        run: choco install ninja --yes --no-progress

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: ci-windows-x64-cuda-13.3
          evict-old-files: 1d

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DGGML_NATIVE=OFF ^
            -DGGML_BACKEND_DL=ON ^
            -DGGML_CUDA=ON ^
            -DGGML_CUDA_CUB_3DOT2=ON ^
            -DLLAMA_BUILD_SERVER=ON ^
            -DLLAMA_BUILD_BORINGSSL=ON ^
            -DGGML_RPC=ON

      - name: Build CUDA backend and server
        shell: cmd
        run: |
          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS% --target ggml-cuda llama-server
