name: CI (Windows CPU)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-cpu.yml'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/build-cpu.yml'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  windows-x64-cpu:
    name: Windows x64 CPU build and tests
    runs-on: windows-2025

    steps:
      - name: Clone
        uses: actions/checkout@v6

      - name: Install Ninja
        shell: pwsh
        run: choco install ninja --yes --no-progress

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: ci-windows-x64-cpu-static
          variant: ccache
          evict-old-files: 1d

      - name: Configure
        shell: pwsh
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" `
            -DCMAKE_TOOLCHAIN_FILE=cmake/x64-windows-llvm.cmake `
            -DGGML_NATIVE=OFF `
            -DLLAMA_BUILD_SERVER=ON `
            -DLLAMA_BUILD_BORINGSSL=ON `
            -DGGML_RPC=ON `
            -DBUILD_SHARED_LIBS=OFF

      - name: Build
        shell: pwsh
        run: cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS

      - name: Test
        shell: pwsh
        run: ctest --test-dir build -L main -C Release --verbose --timeout 900
