name: Server (Windows)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Commit SHA1 to build
        required: false
        type: string
      slow_tests:
        description: Run slow tests
        required: true
        default: false
        type: boolean
  push:
    branches:
      - master
    paths:
      - '.github/workflows/server.yml'
      - '**/CMakeLists.txt'
      - '**/Makefile'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - 'tools/server/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/server.yml'
      - '**/CMakeLists.txt'
      - '**/Makefile'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - 'tools/server/**'

env:
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1
  LLAMA_ARG_LOG_VERBOSITY: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows x64 server tests
    runs-on: windows-2025

    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.sha || github.event.pull_request.head.sha || github.sha }}

      - name: Install Ninja
        shell: pwsh
        run: choco install ninja --yes --no-progress

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: server-windows-x64
          evict-old-files: 1d

      - name: Build
        shell: pwsh
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" `
            -DCMAKE_TOOLCHAIN_FILE=cmake/x64-windows-llvm.cmake `
            -DLLAMA_BUILD_BORINGSSL=ON `
            -DGGML_SCHED_NO_REALLOC=ON
          cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS --target llama-server

      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          pip-install: -r tools/server/tests/requirements.txt

      - name: Tests
        shell: pwsh
        run: |
          Set-Location tools/server/tests
          $env:PYTHONIOENCODING = ':replace'
          pytest -v -x -m 'not slow'

      - name: Slow tests
        if: ${{ inputs.slow_tests }}
        shell: pwsh
        run: |
          Set-Location tools/server/tests
          $env:PYTHONIOENCODING = ':replace'
          $env:SLOW_TESTS = '1'
          pytest -v -x
